/* liteparse_php - Auto-generated C header. Do not edit by hand. */

#ifndef LITEPARSE_PHP_H
#define LITEPARSE_PHP_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ParserHandle {
  uint8_t _private[0];
} ParserHandle;

typedef struct ResultHandle {
  uint8_t _private[0];
} ResultHandle;

typedef struct ScreenshotListHandle {
  uint8_t _private[0];
} ScreenshotListHandle;

/**
 * Returns a pointer to the current thread's last error message, or NULL if
 * none is set. Valid until the next call that sets or clears the error on
 * this thread.
 */
const char *liteparse_get_last_error(void);

void liteparse_clear_last_error(void);

/**
 * Cheap per-page complexity pre-check (no OCR, no rendering) — returns a
 * JSON array of `PageComplexityStats`, one entry per page. Useful for
 * deciding whether a document needs OCR before committing to a full parse.
 * Returns NULL and sets the last error on failure.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by
 * `liteparse_parser_new`. `path` must be a valid NUL-terminated C string.
 */
char *liteparse_parser_is_complex_file(const struct ParserHandle *handle, const char *path);

/**
 * Same as `liteparse_parser_is_complex_file`, from in-memory bytes.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by
 * `liteparse_parser_new`. `data` must point to at least `len` readable
 * bytes.
 */
char *liteparse_parser_is_complex_bytes(const struct ParserHandle *handle,
                                        const uint8_t *data,
                                        uintptr_t len);

/**
 * Create a new parser from a JSON-encoded `LiteParseConfig`. Pass NULL (or
 * `"null"`) to use all defaults. Returns NULL and sets the last error on
 * invalid JSON.
 *
 * # Safety
 * `config_json` must be null or a valid NUL-terminated C string.
 */
struct ParserHandle *liteparse_parser_new(const char *config_json);

/**
 * # Safety
 * `handle` must be null or a value previously returned by
 * `liteparse_parser_new` and not yet freed.
 */
void liteparse_parser_free(struct ParserHandle *handle);

/**
 * Parse a document from a file path. Returns NULL and sets the last error
 * on failure.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by
 * `liteparse_parser_new`. `path` must be a valid NUL-terminated C string.
 */
struct ResultHandle *liteparse_parser_parse_file(const struct ParserHandle *handle,
                                                 const char *path);

/**
 * Parse a document from raw in-memory bytes (e.g. a PDF buffer). Returns
 * NULL and sets the last error on failure.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by
 * `liteparse_parser_new`. `data` must point to at least `len` readable
 * bytes.
 */
struct ResultHandle *liteparse_parser_parse_bytes(const struct ParserHandle *handle,
                                                  const uint8_t *data,
                                                  uintptr_t len);

/**
 * Render the parsed document as pretty-printed JSON. Deliberately does
 * *not* go through `liteparse::output::json::format_json` — that formatter
 * backs the `lit` CLI's `--format json` and intentionally drops most
 * `TextItem` fields (font size, fill/stroke color, rotation, links,
 * strikethrough, ...) down to a lean `{text, x, y, width, height,
 * font_name, font_size, confidence}` shape. `ParsedPage` and `TextItem`
 * already derive `Serialize` directly (with internal-only fields marked
 * `#[serde(skip)]`), so serializing `data.result.pages` as-is gives the PHP
 * side every field liteparse extracts per text item, at no extra cost.
 * Returns NULL on error (rare — JSON formatting of already-parsed data does
 * not normally fail). Free the result with `liteparse_string_free`.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_parse_*` function and not yet freed.
 */
char *liteparse_result_json(const struct ResultHandle *handle);

/**
 * Render the parsed document's projected lines as pretty-printed JSON — a
 * middle layer between the flat `liteparse_result_json` (`TextItem`s: one per
 * PDFium text run, no grouping) and `liteparse_result_markdown` (fully
 * reconstructed headings/lists/tables, which can lose structure when a
 * table's columns land in separate layout regions). Each line carries its
 * merged bbox, dominant font/style, `region_path` (the xy-cut column/region
 * position used for table and paragraph grouping), and `spans` (the original
 * `TextItem`s that merged into it, so per-run font/color/text survives even
 * where `line.text` concatenates multiple items).
 *
 * `ProjectedLine` already derives `Serialize` and is a public field on
 * `ParsedPage` — `#[serde(skip)]` there only suppresses it from
 * `ParsedPage`'s own derive, it doesn't stop us serializing it directly, same
 * bypass as `liteparse_result_json`. Returns NULL on error. Free the result
 * with `liteparse_string_free`.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_parse_*` function and not yet freed.
 */
char *liteparse_result_lines_json(const struct ResultHandle *handle);

/**
 * Render the parsed document as plain text with `--- Page N ---` headers.
 * Free the result with `liteparse_string_free`.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_parse_*` function and not yet freed.
 */
char *liteparse_result_text(const struct ResultHandle *handle);

/**
 * Render the parsed document as Markdown, reconstructing headings, lists,
 * tables and figure references from the spatial layout. Free the result
 * with `liteparse_string_free`.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_parse_*` function and not yet freed.
 */
char *liteparse_result_markdown(const struct ResultHandle *handle);

/**
 * Number of pages in the parsed document.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_parse_*` function and not yet freed.
 */
uintptr_t liteparse_result_page_count(const struct ResultHandle *handle);

/**
 * # Safety
 * `handle` must be null or a value previously returned by a
 * `liteparse_parser_parse_*` function and not yet freed.
 */
void liteparse_result_free(struct ResultHandle *handle);

/**
 * Render document pages to PNG screenshots. `page_numbers` (1-based) selects
 * which pages to render; pass NULL (or `page_numbers_len == 0`) for all
 * pages. Returns NULL and sets the last error on failure.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by
 * `liteparse_parser_new`. `path` must be a valid NUL-terminated C string.
 * `page_numbers` must be null or point to at least `page_numbers_len`
 * readable `u32`s.
 */
struct ScreenshotListHandle *liteparse_parser_screenshot_file(const struct ParserHandle *handle,
                                                              const char *path,
                                                              const uint32_t *page_numbers,
                                                              uintptr_t page_numbers_len);

/**
 * Same as `liteparse_parser_screenshot_file`, from in-memory bytes.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by
 * `liteparse_parser_new`. `input_data` must point to at least `input_len`
 * readable bytes. `page_numbers` must be null or point to at least
 * `page_numbers_len` readable `u32`s.
 */
struct ScreenshotListHandle *liteparse_parser_screenshot_bytes(const struct ParserHandle *handle,
                                                               const uint8_t *input_data,
                                                               uintptr_t input_len,
                                                               const uint32_t *page_numbers,
                                                               uintptr_t page_numbers_len);

/**
 * Number of screenshots in the list.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_screenshot_*` function and not yet freed.
 */
uintptr_t liteparse_screenshot_list_len(const struct ScreenshotListHandle *handle);

/**
 * 1-based page number of the screenshot at `idx`, or 0 if out of range.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_screenshot_*` function and not yet freed.
 */
uint32_t liteparse_screenshot_page_number(const struct ScreenshotListHandle *handle, uintptr_t idx);

/**
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_screenshot_*` function and not yet freed.
 */
uint32_t liteparse_screenshot_width(const struct ScreenshotListHandle *handle, uintptr_t idx);

/**
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_screenshot_*` function and not yet freed.
 */
uint32_t liteparse_screenshot_height(const struct ScreenshotListHandle *handle, uintptr_t idx);

/**
 * Borrowed pointer to the PNG bytes of the screenshot at `idx`, valid until
 * the list is freed. Writes the byte length to `out_len`. Returns NULL (and
 * writes 0 to `out_len`) if `idx` is out of range.
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_screenshot_*` function and not yet freed. `out_len`
 * must be null or a valid pointer to a writable `usize`.
 */
const uint8_t *liteparse_screenshot_bytes(const struct ScreenshotListHandle *handle,
                                          uintptr_t idx,
                                          uintptr_t *out_len);

/**
 * # Safety
 * `handle` must be null or a value previously returned by a
 * `liteparse_parser_screenshot_*` function and not yet freed.
 */
void liteparse_screenshot_list_free(struct ScreenshotListHandle *handle);

/**
 * Search a parsed document's text items for phrase matches, returning a
 * JSON array of `{page_number, text, x, y, width, height}` objects (one per
 * match, in document order). Matches that span multiple text items are
 * merged into a single entry with a combined bounding box. Returns NULL and
 * sets the last error on failure (e.g. invalid `phrase` pointer).
 *
 * # Safety
 * `handle` must be a valid, non-null pointer returned by a
 * `liteparse_parser_parse_*` function and not yet freed. `phrase` must be a
 * valid NUL-terminated C string.
 */
char *liteparse_search(const struct ResultHandle *handle,
                       const char *phrase,
                       int32_t case_sensitive);

/**
 * Free a string previously returned by any `liteparse_*` function that
 * documents its return value as an owned string (e.g.
 * `liteparse_result_json`, `liteparse_result_text`).
 */
void liteparse_string_free(char *ptr);

#endif  /* LITEPARSE_PHP_H */
